# Generated by Django 5.1.2 on 2025-02-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='experience',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
