# Generated by Django 5.1.2 on 2025-02-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_professionalprofile_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
